name: Feature Pipeline

on:
  push:
    branches:
      - feature/*

permissions:
  contents: read

env:
  INFRA_DIR: infra/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: sa-east-1

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov mock
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 app/ --ignore=W504

      - name: Test with pytest
        run: |
          pytest --cov=. -vv --cov-fail-under=90 .