name: Feature Pipeline

on:
  push:
    branches:
      - feature/*

permissions:
  contents: read

env:
  INFRA_DIR: infra/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: sa-east-1

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov mock
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 app/ --ignore=W504

      - name: Test with pytest
        run: |
          pytest --cov=. -vv --cov-fail-under=90 .

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    needs: python
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Generate Terraform S3 Backend Config
        working-directory: ${{ env.INFRA_DIR }}
        run: |
          echo "bucket = \"${{ secrets.BUCKET_TERRAFORM }}\"" >> config.aws.tfbackend
          echo "key = \"$(basename $(git rev-parse --show-toplevel))\"" >> config.aws.tfbackend
          echo "region = \"${{ env.AWS_DEFAULT_REGION }}\"" >> config.aws.tfbackend

      - name: Terraform Init
        working-directory: ${{ env.INFRA_DIR }}
        run: |
          terraform init -backend-config=config.aws.tfbackend

      - name: Terraform Validate
        working-directory: ${{ env.INFRA_DIR }}
        run: |
          terraform validate -backend-config=config.aws.tfbackend

      - name: Terraform Plan
        working-directory: ${{ env.INFRA_DIR }}
        run: |
          terraform plan -backend-config=config.aws.tfbackend