name: Homolog Pipeline

on:
  push:
    branches:
      - homolog

permissions:
  contents: write
  pull-requests: write

env:
  INFRA_DIR: infra/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: sa-east-1

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.INFRA_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run terraform
        run: |
            echo "Terraform is running to deploy the infrastructure"

  cpr:
    name: Create PR to main
    runs-on: ubuntu-latest
    needs: terraform
    env:
      GH_TOKEN: ${{ secrets.GH_SYSTEM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Branch Name
        id: branch
        run: |
          echo "::set-output name=name::$(git rev-parse --abbrev-ref HEAD)"

      - name: Verify If PR already exists
        id: pr
        run: |
          echo "::set-output name=exists::false"
          gh pr list --base main --state open | \
            grep ${{ steps.branch.outputs.name }} && echo "::set-output name=exists::true" || \
            exit 0

      - name: Create PR
        if: steps.pr.outputs.exists == 'false'
        run: |
          gh pr create \
            --title "Auto PR: ${{ steps.branch.outputs.name }} > main" \
            --body "Brief resume\n\nDUE DATE: yyyy-mm-ddTHH:MM:ss" \
            --base "main"
            --auto
