name: PR Validation Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  validate:
    name: PR Validation
    runs-on: ubuntu-latest
    outputs:
      due_date: ${{ steps.due_date.outputs.value }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get PR Number
      id: pr
      run: |
        echo "::set-output name=number::$(echo $GITHUB_REF | cut -d'/' -f3)"

    - name: Validate PR Message
      id: due_date
      run: |
        curl -X POST -s ${{ secrets.API_GTW_URL }}/call \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "${{ github.repository }}",
            "pr_number": ${{ steps.pr.outputs.number }},
          }' > res.json

        echo "::set-output name=due_date::$(cat res.json | jq -r '.dueDate')"
        test $(cat res.json | jq -r '.isValid') = "true"

  schedule:
    name: Schedule Implantation in Production
    runs-on: ubuntu-latest
    needs: validate
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name:  Schedule Implantation
      run: |
        curl -X POST -s ${{ secrets.API_GTW_URL }}/call \
          -H "Content-Type: application/json" \
          -d '{
            "repository": "${{ github.repository }}",
            "workflow_id": ${{ github.run_id }},
            "due_date": "${{ needs.validate.outputs.due_date }}",
          }'

  await:
    name: Await Implantation
    runs-on: ubuntu-latest
    needs: [schedule, validate]
    environment: prod
    steps:
      - name: Get PR Number
        id: pr
        run: |
          echo "::set-output name=number::$(echo $GITHUB_REF | cut -d'/' -f3)"

      - name: Deploying in Production
        run: |
          echo "Deploying in Production at  ${{ needs.schedule.outputs.due_date }}"
          echo "The PR ${{ steps.pr.outputs.number }} will be automatically closed."
