name: Production Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  INFRA_DIR: infra/

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.INFRA_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run terraform
        run: |
            echo "Terraform is running to deploy the infrastructure"
